version: '3'
env:
  RENDER_DIR: .rendered
tasks:
  lint-check:
    desc: 🧹 Check whether the codebase is linted
    cmds:
        - echo "🧹 Linting"
        - task: install-dev
        - cd ./$RENDER_DIR/infra && uv run ruff format --check --diff .
        - cd ./$RENDER_DIR/infra && uv run ruff check --diff .
        - cd ./$RENDER_DIR/infra && uv tool run ty@0.0.1a34 check --verbose .
  validate-windows-compatibility:
    desc: "Validate that file paths don't contain characters illegal on Windows"
    cmds:
      - cmd: |
          offending_files=$(find . -type f -exec basename {} \; | grep '[\<\>\:\"\/\|\?\*]' | sort -u)
          if [ -n "$offending_files" ]; then
            echo "Files with Windows-incompatible characters found:"
            for file in $offending_files; do
              find . -type f -name "$file"
            done
            exit 1
          fi
        platforms: [linux, darwin]

  copyright:
    aliases: [license]
    desc: 📜 Apply license headers
    cmds:
      - echo "📜 Applying license headers"
      - docker run  --rm -v $PWD:/github/workspace ghcr.io/apache/skywalking-eyes/license-eye:eb0e0b091ea41213f712f622797e37526ca1e5d6 -v info -c .licenserc.yaml header fix
  copyright-check:
    aliases: [license-check]
    desc: 📜 Checking for license headers
    cmds:
      - echo "📜 Checking license headers"
      - docker run  --rm -v $PWD:/github/workspace ghcr.io/apache/skywalking-eyes/license-eye:eb0e0b091ea41213f712f622797e37526ca1e5d6 -v info -c .licenserc.yaml header check
  render-template:
    desc: "Render template"
    cmds:
      - echo "Rendering template"
      # Clean up the existing rendered directory except for .venv to speed up rendering and avoid conflict checks
      - cd ./$RENDER_DIR/ && [ -d . ] && find . -mindepth 1 -maxdepth 1 ! -name '.venv' -exec rm -rf {} + || true
      - uvx copier copy . ./$RENDER_DIR --defaults --vcs-ref=HEAD
      - cp ./fixtures/infra/pyproject.toml ./$RENDER_DIR/infra/pyproject.toml
      - cp ./fixtures/infra/__init__.py ./$RENDER_DIR/infra/infra/__init__.py
      - cp ./fixtures/infra/Pulumi.yaml ./$RENDER_DIR/infra/Pulumi.yaml
      - touch ./$RENDER_DIR/infra/__init__.py
  install-dev:
    desc: "Install dev"
    cmds:
      - echo "Installing dev for LLM"
      - task: render-template
      - cd ./$RENDER_DIR/infra && uv sync --extra dev --quiet
