---
# https://taskfile.dev
version: '3'
tasks:
  req:
    cmds:
      - echo "Updating local dependencies"
      - uv sync --all-extras
      - uv pip install git+https://github.com/datarobot-forks/litellm@mattn/add-datarobot-support-to-litellm
    silent: true
  lint:
    cmds:
      - echo "Linting the codebase"
      - uv run ruff check . --fix
      - uv run ruff format .
      - uv run mypy --pretty .
      - uv run yamlfix custom_model
    silent: true
  test:
    cmds: [echo "Running pytest on tests", uv run pytest -vv ./tests/]
    silent: true
